#!/bin/bash

# Full path to the text file containing IP addresses
FILE_PATH="/home/anthony/SM.txt"

# Associative array to store IP address nicknames
declare -A IP_NICKNAMES=(
  ["10.0.4.11"]="R&R-SAN"
  ["10.0.4.100"]="DCIM-SAN"
  ["10.51.0.21"]="DCIM-DAL"
  ["172.18.5.231"]="DCIM-CHAR"
  ["10.38.0.100"]="DCIM-SEA"
  ["10.50.1.99"]="DCIM-JAX"
  ["199.73.53.197"]="Panel"
  ["8.34.125.237"]="Website"
  
)

# Define color codes for formatting
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
LIGHT_BLUE='\033[1;34m'
NC='\033[0m' # No color

# Read each IP address from the text file and check ping status
while IFS= read -r ip_address; do
  nickname="${IP_NICKNAMES[$ip_address]}"
  if ping -c 1 "$ip_address" >/dev/null; then
    echo -e "${LIGHT_GREEN}Pass: $nickname ($ip_address)${NC}"
  else
    echo -e "${LIGHT_RED}Fail: $nickname ($ip_address) Check Manually${NC}"
    echo
  fi
done < "$FILE_PATH"

